language: node_js
node_js:
 - 12.12.0
before_install:
  - npm i -g firebase-tools
script:
  - npm run start
notifications:
  email: false
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
branches:
  only:
    - master